# This workflow will install Python dependencies, run tests with tox across Python 3.10-3.14

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install tox ruff pytest pytest-cov

    - name: Lint with ruff
      run: |
        ruff check tests/
        ruff format --check tests/

    - name: Build and test with tox
      run: |
        pip install -e .
        pytest tests/
